
import React,{useState}from"react";
const DISCORD="https://discord.gg/WPH5Xc58cm";
const ADMIN_PASS="admtauros";
const prices={mistos:4,reais:5,premium:9};
const produtos=[
{id:"discord",titulo:"Discord",subtitulo:"Veja nossos produtos",preco:"",img:"discord",tipo:"categoria"},
{id:"membros",titulo:"Membros Discord",subtitulo:"Servidores com membros",preco:"A partir de R$ 4,00",img:"membros",tipo:"membros"},
{id:"nitro",titulo:"Nitro Discord",subtitulo:"Nitro para sua conta",preco:"R$ 6,50",img:"nitro",tipo:"fixo"},
{id:"designer",titulo:"Designer",subtitulo:"Designer para seu servidor",preco:"R$ 65,00",img:"designer",tipo:"fixo"}];
function moeda(v){return v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
export default function App(){
const[produto,setProduto]=useState(null),[discordAberto,setDiscordAberto]=useState(false),[tipoMembro,setTipoMembro]=useState("mistos"),[quantidade,setQuantidade]=useState(100),[pago,setPago]=useState(false);
const[login,setLogin]=useState(false),[criarConta,setCriarConta]=useState(false),[email,setEmail]=useState(localStorage.getItem("st_email")||""),[logado,setLogado]=useState(!!localStorage.getItem("st_email"));
const[adminLogin,setAdminLogin]=useState(false),[adminAberto,setAdminAberto]=useState(false),[senhaAdmin,setSenhaAdmin]=useState(""),[pix,setPix]=useState(localStorage.getItem("st_pix")||""),[qr,setQr]=useState(localStorage.getItem("st_qr")||""),[vendas,setVendas]=useState(()=>JSON.parse(localStorage.getItem("st_vendas")||"[]"));
const precoMembro=moeda((quantidade/100)*prices[tipoMembro]);
function abrirProduto(p){if(p.id==="discord"){setDiscordAberto(!discordAberto);return}setProduto(p);setPago(false)}
function entrarConta(novo=false){if(!email.includes("@"))return alert("Digite um email válido.");localStorage.setItem("st_email",email);setLogado(true);setLogin(false);setCriarConta(false);alert(novo?"Conta criada com sucesso!":"Login realizado!")}
function entrarAdmin(){if(senhaAdmin===ADMIN_PASS){setAdminLogin(false);setAdminAberto(true);setSenhaAdmin("")}else alert("Senha admin incorreta.")}
function salvarAdmin(){localStorage.setItem("st_pix",pix);localStorage.setItem("st_qr",qr);alert("Configurações salvas!")}
function uploadQr(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setQr(String(r.result));r.readAsDataURL(f)}
function copiarPix(){if(!pix)return alert("Pix ainda não cadastrado no painel admin.");navigator.clipboard.writeText(pix);alert("Pix copiado!")}
function confirmarPagamento(){const nome=produto?.tipo==="membros"?`${quantidade} Membros ${tipoMembro}`:produto?.titulo;const valor=produto?.tipo==="membros"?precoMembro:produto?.preco;const venda={id:"ST-"+Math.floor(1000+Math.random()*9000),nome,valor,data:new Date().toLocaleString("pt-BR")};const novas=[venda,...vendas];setVendas(novas);localStorage.setItem("st_vendas",JSON.stringify(novas));setPago(true)}
return <div className="page">
<aside className="sidebar">
 <div className="perfil"><div className="taurosLogo"></div><div><b>STORE TAUROS <span>✓</span></b><small>Loja oficial</small></div></div>
 <p>MENU</p><a href="#inicio" className="active">⌂ <span>Início</span></a><a href="#produtos">▣ <span>Produtos</span></a><button onClick={()=>setDiscordAberto(!discordAberto)}>💬 <span>Discord</span><em>⌄</em></button><a href="#pix">◇ <span>Pix</span></a><button onClick={()=>window.open(DISCORD,"_blank")}>🎧 <span>Suporte</span></button>
 <p>ADMINISTRAÇÃO</p><button className="adminSide" onClick={()=>setAdminLogin(true)}>🛡 <span>Painel Admin</span></button><button onClick={()=>setAdminLogin(true)}>↪ <span>Login Admin</span></button>
 <p>CONTA</p><button onClick={()=>setLogin(true)}>↪ <span>{logado?"Minha conta":"Entrar"}</span></button><button onClick={()=>setCriarConta(true)}>☊ <span>Criar conta</span></button>
 <div className="discordBox"><b>Acessar Discord</b><small>Comunidade oficial</small><button onClick={()=>window.open(DISCORD,"_blank")}>Abrir</button></div>
</aside>
<main>
 <section id="inicio" className="hero"><div className="heroText"><h1>Bem-Vindo(a) à<br/><span>Store Tauros!</span></h1><p>Aqui você encontra tudo para elevar sua experiência, com produtos digitais premium, entrega automática e suporte dedicado!</p><div className="beneficios"><div>⚡ <b>Entrega automática</b><small>Instantânea</small></div><div>🛡 <b>100% Seguro</b><small>Dados protegidos</small></div><div>🎧 <b>Suporte 24/7</b><small>Sempre disponível</small></div></div></div><div className="heroLogo"><div className="bullImage"></div><h2>TAUROS</h2><span>STORE</span></div></section>
 <section id="produtos" className="produtos"><h2>Nossos Produtos</h2><p>Produtos digitais premium para você!</p><div className="cards">{produtos.map(p=><button className="card" key={p.id} onClick={()=>abrirProduto(p)}><div className={`cardImg ${p.img}`}><span>{p.img==="discord"?"💬":p.img==="membros"?"👥":p.img==="nitro"?"💎":"◉"}</span></div><div className="cardInfo"><h3>{p.titulo}</h3><p>{p.subtitulo}</p><i>→</i></div></button>)}</div>{discordAberto&&<div className="discordDropdown"><h3>Produtos Discord</h3><div>{produtos.filter(p=>p.id!=="discord").map(p=><button key={p.id} onClick={()=>abrirProduto(p)}><b>{p.titulo}</b><small>{p.preco}</small></button>)}</div></div>}</section>
 <section id="pix" className="pagamento"><h2>Pagamento</h2><p>Formas de pagamento</p><button className="pixCard" onClick={()=>alert("A chave Pix aparece apenas após clicar em comprar.")}><div className="pixIcon">◆</div><div><b>Apenas Pix</b><small>Pagamento via PIX</small></div><span>→</span></button></section><div className="help"><b>Precisa de ajuda?</b><span>Entre no nosso Discord!</span><button onClick={()=>window.open(DISCORD,"_blank")}>💬</button></div></main>
 {produto&&<div className="modalBg"><div className="modal compra"><button className="close" onClick={()=>setProduto(null)}>×</button><div className={`modalImage ${produto.img}`}></div><div><span className="stock">Disponível</span><h2>{produto.titulo}</h2><p>{produto.subtitulo}</p>{produto.tipo==="membros"?<><strong>{precoMembro}</strong><div className="selects"><select value={tipoMembro} onChange={e=>setTipoMembro(e.target.value)}><option value="mistos">Membros Mistos - R$ 4,00 por 100</option><option value="reais">Membros Reais - R$ 5,00 por 100</option><option value="premium">Membros Premium - R$ 9,00 por 100</option></select><select value={quantidade} onChange={e=>setQuantidade(Number(e.target.value))}>{[100,200,300,400,5000].map(q=><option key={q} value={q}>{q} membros</option>)}</select></div></>:<strong>{produto.preco}</strong>}<div className="pay"><h3>Pagamento Pix</h3><p>{pix||"Pix ainda não cadastrado no painel admin."}</p><button onClick={copiarPix}>Copiar Pix</button>{qr&&<img src={qr} alt="QR Pix"/>}</div>{!pago?<button className="buy" onClick={confirmarPagamento}>Confirmar pagamento</button>:<div className="ok"><h3>✅ Pagamento confirmado!</h3><p>Agora abra o Discord para resgatar seu pedido.</p><a href={DISCORD} target="_blank">Abrir Discord</a></div>}</div></div></div>}
 {(login||criarConta)&&<div className="modalBg"><div className="modal auth"><button className="close" onClick={()=>{setLogin(false);setCriarConta(false)}}>×</button><h2>{criarConta?"Criar conta":"Entrar"}</h2><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha"/>{criarConta&&<input type="password" placeholder="Confirmar senha"/>}<button onClick={()=>entrarConta(criarConta)}>{criarConta?"Criar conta":"Entrar"}</button><p>Login visual salvo neste navegador.</p></div></div>}
 {adminLogin&&<div className="modalBg"><div className="modal auth"><button className="close" onClick={()=>setAdminLogin(false)}>×</button><h2>Login Admin</h2><input type="password" placeholder="Senha: admtauros" value={senhaAdmin} onChange={e=>setSenhaAdmin(e.target.value)} onKeyDown={e=>e.key==="Enter"&&entrarAdmin()}/><button onClick={entrarAdmin}>Entrar</button></div></div>}
 {adminAberto&&<div className="modalBg"><div className="modal admin"><button className="close" onClick={()=>setAdminAberto(false)}>×</button><h2>Painel de Administração</h2><div className="adminGrid"><section><h3>Pix e QR</h3><input placeholder="Chave Pix" value={pix} onChange={e=>setPix(e.target.value)}/><input type="file" accept="image/*" onChange={uploadQr}/>{qr&&<img className="qr" src={qr}/>}<button onClick={salvarAdmin}>Salvar Pix/QR</button></section><section><h3>Vendas</h3><div className="vendas">{vendas.length===0?<p>Nenhuma venda.</p>:vendas.map(v=><div key={v.id}><b>{v.nome}</b><small>{v.valor} • {v.data}</small></div>)}</div><button onClick={()=>{setVendas([]);localStorage.removeItem("st_vendas")}}>Limpar vendas</button></section><section><h3>Discord</h3><p>{DISCORD}</p><button onClick={()=>window.open(DISCORD,"_blank")}>Abrir Discord</button></section></div></div></div>}
</div>}
